swagger: "2.0"
info:
  description: "提供给外部应用使用的用户以及用户组织信息，组织内的dashboard信息，panel信息"
  version: "1.0.0"
  title: "bridgetografana"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "suoyanan354@pingan.com.cn"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "grafana-argus.pingan.com"
basePath: "/v1"
schemes:
- "http"
paths:
    /login:
      post:
        tags:
        - "login"
        summary: "login operation"
        description: "login operation"
        operationId: "login"
        consumes:
        - "application/x-www-form-urlencoded"
        produces:
        - "application/json"
        parameters:
        - name: "account"
          in: "formData"
          type: "string"
          description: "login user account"
        - in: "formData"
          name: "password"
          type: "string"
          description: "login user password"
        responses:
          200:
            description: "login successful"
            schema:
              $ref: "#/definitions/User"
          400:
            description: "Invalid ID supplied"
          404:
            description: "User not found"
    /grouplist:
      get:
        tags: 
        - "grouplist"
        summary: "根据用户名或者用户ID来取得用户所加入的group"
        description: "根据用户名或者用户ID来取得用户所加入的group"
        operationId: "grouplist"
        produces: 
        - "application/json"
        parameters: 
        - name: "user"
          in: "query"
          type: "string"
          description: "用户的名称或者ID"
        responses:
          200:
            description: "success"
            schema:
              items:
                $ref: "#definitions/ApiResponse"
          400:
            description: "Invalid ID supplied"
          404:
            description: "user not found"
    /dashboardlist:
      get:
        tags:
        - "dashboardlist"
        summary: "根据group的ID来取得用户所参与的group的dashboard列表"
        description: "根据group的ID来取得用户所参与的group的dashboard列表"
        operationId: "dashboardlist"
        produces: 
        - "application/json"
        parameters: 
        - name: "user"
          in: "query"
          type: "string"
          description: "用户的名称或者ID"
        - name: "groupname"
          in: "query"
          type: "string"
          description: "group的名称或者ID"
        responses:
          200:
            description: "success"
            schema:
              items:
                $ref: "#definitions/ApiResponse"
          400:
            description: "Invalid ID supplied"
          404:
            description: "group not found"
    /panellist:
      get:
        tags:
        - "panelist"
        summary: "根据用户ID（或者名称）和groupID（或者名称）来取得panel信息列表"
        description: "根据用户ID（或者名称）和groupID（或者名称）来取得panel信息列表" 
        operationId: "panellist"
        produces: 
        - "application/json"
        parameters: 
        - name: "user"
          in: "query"
          type: "string"
          description: "用户的名称或者ID"
        - name: "groupname"
          in: "query"
          type: "string"
          description: "group的名称或者ID"
        - name: "dashboard"
          in: "query"
          type: "string"
          description: "dashboard名称或者ID"
        responses:
          200:
            description: "success"
            schema:
              items:
                $ref: "#definitions/ApiResponse"
          400:
            description: "Invalid ID supplied"
          404:
            description: "dashboard not found"
    /panelinfo:
      get:
        tags: 
        - "panelinfo"
        summary: "取得panel的详细信息（unit单位，title名称，endpoint机器列表，metric指标信息）"
        description: "取得panel的详细信息（unit单位，title名称，endpoint机器列表，metric指标信息）"
        operationId: "panelinfo"
        produces: 
        - "application/json"
        parameters: 
        - name: "user"
          in: "query"
          type: "string"
          description: "用户的名称或者ID"
        - name: "groupname"
          in: "query"
          type: "string"
          description: "group的名称或者ID"
        - name: "dashboard"
          in: "query"
          type: "string"
          description: "dashboard名称或者ID"
        - name: "panel"
          in: "query"
          type: "string"
          description: "panel的名称"
        responses:
          200:
            description: "success"
            schema:
              items:
                $ref: "#definitions/ApiResponse"
          400:
            description: "Invalid ID supplied"
          404:
            description: "panel not found"
    /metricdata:
      post:
        tags: 
        - "metricdata"
        summary: "根据metric和endpoint，起始时间和终止时间来查询一段时间的指标数据点"
        description: "根据metric和endpoint，起始时间和终止时间来查询一段时间的指标数据点"
        operationId: "metricdata"
        consumes:
        - "application/json"
        produces: 
        - "application/json"
        parameters: 
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#definitions/MetricRange"
          description: "查询一个指标的一段时间内的数据点参数"
        responses:
          200:
            description: "success"
            schema:
              items:
                $ref: "#definitions/ApiResponse"
          400:
            description: "Iparams error"
          404:
            description: "panel not found"
      

definitions:
  User:
    type: "object"
    properties:
      Email:
        type: "string"
      Name:
        type: "string"
      UserID:
        type: "string"
  Group:
    type: "object"
    properties:
      Id:
        type: "integer"
        format: "int64"
      Name:
        type: "string"
      Role:
        type: "string"
  Dashboard:
    type: "object"
    properties:
      Id:
        type: "integer"
        format: "int64"
      Title:
        type: "string"
      Uri:
        type: "string"
      Type:
        type: "string"
      IsStarred:
        type: "boolean"
  Panel:
    type: "object"
    properties:
      Name:
        type: "string"
      Metric:
        type: "string"
      Unit:
        type: "string"
      Endpoints:
        type: "array"
        items:
          type: "string"
  Datapoints:
    type: "object"
    properties:
      Name:
        type: "string"
      RangeStart:
        type: "integer"
        format: "int64"
      RangeEnd:
        type: "integer"
        format: "int64"
      Data:
        type: "array"
        items:
          $ref: "#/definitions/PointsArray"
  PointsArray:
    type: "object"
    properties:
      Dstype: 
        type: "string"
      Step:
        type: "integer"
        format: "int64"
      Endpoint:
        type: "string"
      Values:
        type: "array"
        items:
          $ref: "#/definitions/Points"
      counter: 
        type: "string"
  Points:
    type: "object"
    properties:
      Timestamp: 
        type: "integer"
        format: "int64"
      Value:
        type: "integer"
        format: "int64"
  MetricRange:
    type: "object"
    properties:
      RangeStart:
        type: "integer"
        format: "int64"
      RangeEnd:
        type: "integer"
        format: "int64"
      Metric:
        type: "string"
      Endpoint:
        type: "array"
        items:
          type: "string"
  ApiResponse:
    type: "object"
    properties:
      Code:
        type: "integer"
        format: "int32"
      Data:
        type: "object"
      Message:
        type: "string"
